import { createSlice } from "@reduxjs/toolkit"

const initialState = {
    users : [],
    nums : 0
}

const userSlice = createSlice({
    name: "users",
    initialState,
    reducers : {
        // state is current state data
        setUsers:(state,action)=>{
            // payload gives data what we send and it is a action object
            state.users = [...state.users,action.payload]
        },
        deleteUsers : (state,action)=>{
            state.users = state.users.filter((user,index)=>{
                return index !== action.payload
            })
        },
        addNums : (state,action)=>{
            state.nums = state.nums + action.payload
        }
    }
})
export const {setUsers,deleteUsers,addNums} = userSlice.actions
// This line makes the setUsers,deleteUsers and addNums actions available for use elsewhere in your app.

export default userSlice.reducer

// userSlice.reducer: This is the reducer function generated by createSlice.
//  It contains the logic to handle the actions (like setUsers, deleteUsers) and update the state.